from io import BytesIO
from xml.sax.saxutils import escape
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, KeepTogether, PageBreak
from PIL import Image as PILImage


def generate_pdf(data, files):
    output = BytesIO()
    styles = getSampleStyleSheet()
    styles['Heading2'].keepWithNext = True
    styles['Heading3'].keepWithNext = True
    story = []

    def paragraph(text, style="BodyText"):
        return Paragraph(escape(str(text if text is not None else "Unavailable")), styles[style])

    def heading(text):
        story.extend([Spacer(1, 12), paragraph(text, "Heading2")])

    def table(headers, rows, widths):
        cells = [[paragraph(v) for v in headers]] + [[paragraph(v) for v in row] for row in rows]
        t = Table(cells, colWidths=widths, repeatRows=1, hAlign="LEFT")
        t.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e0e7ff")),
                              ("VALIGN", (0, 0), (-1, -1), "TOP"), ("GRID", (0, 0), (-1, -1), .3, colors.lightgrey),
                              ("BOTTOMPADDING", (0, 0), (-1, -1), 7)]))
        story.append(t)

    story.append(paragraph("AI CCTV Intelligence & Investigation Platform", "Title"))
    story.append(paragraph("Gujarat Police Hackathon Demo", "Heading2"))
    for label, value in [("Reference", data["investigation_id"]), ("Vehicle", data["vehicle_plate"]),
                         ("Generated (UTC)", data["generated_at"]), ("Generated by", data["generated_by"]["name"])]:
        story.append(paragraph(f"{label}: {value}"))
    heading("Detection summary")
    for key, value in data["summary"].items():
        story.append(paragraph(f"{key.replace('_', ' ').title()}: {value}"))
    story.append(paragraph(data["association_note"]))
    heading("Camera timeline (UTC)")
    cameras = {c["id"]: c for c in data["cameras"]}
    rows = []
    for d in data["detections"]:
        c = cameras.get(d["camera_id"], {})
        rows.append([c.get("camera_name", d["camera_id"]), d["timestamp"],
                     f"{c.get('latitude')} / {c.get('longitude')}", data["vehicle_plate"],
                     d["confidence"], d["detection_type"]])
    table(["Camera", "Time", "Lat / Lon", "Plate*", "Confidence", "Type"], rows, [75, 100, 75, 85, 65, 55])
    story.append(paragraph("*Plate is associated from the vehicle sighting; object confidence is not plate confidence."))
    heading("Ordered route / camera locations")
    table(["Camera / location", "Time (UTC)", "Coordinates", "Transition"],
          [[f"{r['camera_name']} / {r['location']}", r["timestamp"], f"{r['latitude']} / {r['longitude']}", r["transition_status"]] for r in data["route"]], [145, 110, 95, 105])
    heading("Related alerts")
    for a in data["alerts"]:
        story.append(paragraph(f"#{a['id']} | {a['timestamp']} | Camera {a['camera_id']} | {a['severity']} | {a['alert_type']}: {a['message']}"))
    if not data["alerts"]:
        story.append(paragraph("No alerts linked by snapshot provenance."))
    story.append(PageBreak())
    heading("Selected evidence")
    for e in data["evidence"]:
        start = len(story)
        story.append(paragraph(f"Evidence #{e['id']} - {e['evidence_type']}", "Heading3"))
        for text in [f"Time (UTC): {e['timestamp']} | Camera: {e['camera_id']} | Plate: {e['vehicle_plate']}",
                     e["description"], f"File: {e['file_status']}", f"SHA-256: {e['sha256'] or 'No file'}"]:
            story.append(paragraph(text))
        if e['evidence_type'] == 'ROUTE_TRACE':
            story.append(paragraph('Saved route: ' + ' -> '.join(r['camera_name'] for r in e['details']['route'])))
        content = files.get(e["id"])
        if content:
            with PILImage.open(BytesIO(content)) as im:
                im.verify()
            image = Image(BytesIO(content))
            image._restrictSize(420, 220)
            story.extend([Spacer(1, 8), image])
        block = story[start:]
        del story[start:]
        story.append(KeepTogether(block))
    heading("Human verification required")
    story.append(paragraph("This is an AI-assisted investigation report for a hackathon demonstration. AI detections, plate readings, associations and inferred routes are investigative leads, not conclusive evidence. A human investigator must verify the original recordings and context. SHA-256 verifies file consistency, not authenticity or a complete chain of custody."))

    def footer(canvas, doc):
        canvas.setFont("Helvetica", 8)
        canvas.drawString(40, 24, "AI-assisted | Human verification required | Times UTC")
        canvas.drawRightString(A4[0] - 40, 24, f"Page {doc.page}")

    SimpleDocTemplate(output, pagesize=A4, rightMargin=40, leftMargin=40, topMargin=35, bottomMargin=40).build(story, onFirstPage=footer, onLaterPages=footer)
    return output.getvalue()
