import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Check, X, Camera, ScanLine, Search, ShieldCheck, Activity, Command, MousePointer2, AlignLeft, AlignCenter, AlignRight, Layers, Video } from 'lucide-react';
import { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import './Landing.css';

export function Brand() {
  return <Link to="/" className="nexus-brand" aria-label="Nexus home"><Command size={25} strokeWidth={2.5} />NEXUS<span>.</span></Link>;
}

function EntryForm({ dark = false }) {
  const { user } = useAuth();
  return <div className={`entry-actions ${dark ? 'entry-dark' : ''}`}><Link className="display-button" to={user ? '/dashboard' : '/login'}>{user ? 'OPEN COMMAND CENTER' : 'ENTER COMMAND CENTER'}<ArrowUpRight size={22} /></Link><span><ShieldCheck size={14} /> Built for authorized teams</span></div>;
}

function ProductPreview() {
  const [view, setView] = useState('Overview');
  return <div className="product-preview" id="preview">
    <div className="preview-bar"><div className="traffic-lights"><i /><i /><i /></div><span>nexus / command center</span><span className="preview-label">INTERACTIVE PREVIEW</span></div>
    <div className="preview-body">
      <aside className="preview-sidebar"><strong>NEXUS<span>.</span></strong><small>WORKSPACE</small>{[['Overview', Layers], ['Cameras', Camera], ['Detection', ScanLine]].map(([label, Icon]) => <button key={label} onClick={() => setView(label)} className={view === label ? 'selected' : ''}><Icon size={15} />{label}</button>)}<div className="preview-profile"><span>NX</span><div>Demo workspace<small>Sample data</small></div></div></aside>
      <div className="preview-canvas"><div className="preview-heading"><div><small>YOUR OPERATION. IN FOCUS.</small><h3>{view === 'Overview' ? 'THE BIG PICTURE.' : view === 'Cameras' ? 'EVERY ANGLE.' : 'FIND THE SIGNAL.'}</h3></div><span className="sample-tag">DEMO</span></div><div className="preview-stats">{(view === 'Cameras' ? [['12', 'Connected cameras'], ['04', 'Locations'], ['01', 'Needs review']] : view === 'Detection' ? [['248', 'Objects detected'], ['86', 'Plates read'], ['03', 'Review alerts']] : [['12', 'Camera feeds'], ['248', 'Detections'], ['03', 'Review alerts']]).map(([value, label]) => <div key={label}><small>{label}</small><strong>{value}<Activity size={18} /></strong></div>)}</div><div className="camera-scene"><div className="scene-road" /><div className="scene-building building-one" /><div className="scene-building building-two" /><div className="scene-car car-one" /><div className="scene-car car-two" /><div className="detection-box"><span>VEHICLE · SAMPLE</span></div><span className="scene-caption"><i /> NORTH ENTRANCE · ILLUSTRATION</span><div className="floating-cursor"><MousePointer2 size={24} fill="#ffe17c" /><span>Operator</span></div></div></div>
      <aside className="preview-properties"><small>INSPECTION PANEL</small><h4>THE DETAILS.</h4><label>Source</label><div>North entrance <Camera size={13} /></div><label>Object type</label><div>Vehicle <ScanLine size={13} /></div><label>View alignment</label><div><AlignLeft size={16} /><AlignCenter size={16} /><AlignRight size={16} /></div><label>Highlight color</label><div><i className="color-swatch" />#FFE17C</div><p><ShieldCheck size={17} />Every detection starts a review. You make the call.</p></aside>
    </div>
  </div>;
}

export default function Landing() {
  const { user } = useAuth();
  return <div className="landing"><a className="skip-link" href="#main">Skip to content</a>
    <header className="landing-header"><div className="landing-nav"><Brand /><nav aria-label="Main navigation"><a href="#features">The platform</a><a href="#how-it-works">How it works</a><a href="#why-nexus">Why NEXUS</a></nav><div className="nav-actions"><Link to="/login">Login</Link><Link className="nav-cta" to={user ? '/dashboard' : '/login'}>Get started <ArrowUpRight size={16} /></Link></div></div></header>
    <main id="main"><section className="landing-hero grid-paper"><div className="eyebrow"><i /> INTELLIGENCE, WITHOUT THE BLIND SPOTS</div><h1>MORE SIGNAL.<br />LESS <span className="word-highlight">NOISE.</span></h1><p>Your cameras see everything. Know what matters.<br className="desktop-break" /> Turn scattered footage into clear, actionable intelligence.</p><EntryForm /><a className="preview-jump" href="#preview">Take a closer look <ArrowRight size={15} /></a><ProductPreview /><div className="hero-footnote"><span>ONE WORKSPACE. THE WHOLE PICTURE.</span><span>CAMERAS → DETECTIONS → EVIDENCE</span></div></section>
    <section className="capability-strip" aria-label="Platform capabilities"><p>ONE CONNECTED<br /><strong>INTELLIGENCE WORKFLOW</strong></p>{[[Camera, 'Live monitoring'], [ScanLine, 'Object detection'], [Search, 'Evidence search'], [ShieldCheck, 'Human review']].map(([Icon, label]) => <span key={label}><Icon size={23} />{label}</span>)}</section>
    <section className="contrast-section" id="why-nexus"><div className="contrast-half old-way"><span className="eyebrow">01 / TIME FOR A BETTER WAY</span><h2>MORE FOOTAGE.<br />LESS CLARITY.</h2><h3>THE OLD WAY</h3>{['Disconnected feeds and endless tabs.', 'Hours spent scrubbing through video.', 'Important context lost in the noise.'].map(text => <p key={text}><X size={18} />{text}</p>)}</div><div className="contrast-half new-way"><span className="eyebrow">YOUR NEXT CHAPTER</span><h2>ONE WORKSPACE.<br /><span>A CLEARER VIEW.</span></h2><h3>THE NEXUS WAY</h3>{['Bring camera feeds into one command center.', 'Search detections and review relevant footage.', 'Keep snapshots and source context together.'].map(text => <p key={text}><Check size={18} />{text}</p>)}</div></section>
    <section className="features-section section-container" id="features"><div className="section-heading"><div><span className="eyebrow">02 / BUILT FOR THE BIG PICTURE</span><h2>LESS FRICTION.<br />MORE <span className="underlined">FOCUS.</span></h2></div><p>From the first frame to the final review.<br />Everything you need to connect the dots.</p></div><div className="feature-grid">
      <article className="feature-card feature-wide"><div className="feature-top"><Camera size={25} /><span>01 / MONITOR</span></div><h3>EVERY ANGLE. ONE PLACE.</h3><p>Organize your cameras, check stream health, and keep your operation in view.</p><div className="mini-feeds">{['NORTH ENTRANCE', 'MAIN GATE', 'PARKING AREA'].map((text, i) => <div key={text}><div className={`feed-art art-${i}`}><ScanLine size={42} /></div><span><i />{text}</span></div>)}</div></article>
      <article className="feature-card feature-dark"><div className="feature-top"><ScanLine size={25} /><span>02 / DETECT</span></div><h3>FIND THE SIGNAL.</h3><p>Object detection and plate reading turn footage into searchable records.</p><div className="signal-visual" aria-hidden="true"><div /><div /><div /><ScanLine size={54} /></div><span className="visual-caption">FROM PIXELS TO CONTEXT</span></article>
      <article className="feature-card feature-yellow"><div className="feature-top"><Search size={25} /><span>03 / INVESTIGATE</span></div><h3>FOLLOW THE THREAD.</h3><p>Filter detections, inspect snapshots, and trace records back to their source.</p><div className="search-illustration"><Search size={18} /><span>Search. Filter. Connect.</span><ArrowRight size={19} /></div><div className="record-lines"><span /><span /><span /></div></article>
      <article className="feature-card feature-wide"><div className="feature-top"><ShieldCheck size={25} /><span>04 / REVIEW</span></div><h3>INTELLIGENCE WITH CONTEXT.</h3><p>Review alerts alongside evidence. Keep human judgment at the center of every decision.</p><div className="review-illustration"><div className="review-icon"><ShieldCheck size={30} /></div><div><strong>Ready for a closer look</strong><span>Source footage + snapshot + detection context</span></div><span className="review-pill">HUMAN REVIEW</span></div><div className="review-flow"><span>Detect</span><ArrowRight size={17} /><span>Inspect</span><ArrowRight size={17} /><span>Decide</span></div></article>
    </div></section>
    <section className="how-section" id="how-it-works"><div className="section-container how-grid"><div className="how-title"><span className="eyebrow">03 / FROM SETUP TO SIGNAL</span><h2>LESS SETUP.<br />MORE<br /><span>LET’S GO.</span></h2><p>A straightforward workflow.<br />A clearer picture at every step.</p></div><div className="steps">{[['01', 'CONNECT YOUR CAMERAS.', 'Add your camera sources and locations. Check stream health from one workspace.'], ['02', 'PUT FOOTAGE TO WORK.', 'Monitor supported streams or upload a video to run object detection and plate reading.'], ['03', 'TURN CONTEXT INTO CLARITY.', 'Search your records, review alerts, and examine the supporting evidence.']].map(([number, title, description]) => <article key={number}><span className="step-number">{number}</span><div><h3>{title}</h3><p>{description}</p></div><ArrowUpRight size={23} /></article>)}</div></div></section>
    <section className="use-cases section-container"><div className="section-heading"><div><span className="eyebrow">04 / ONE PLATFORM. MANY PERSPECTIVES.</span><h2>BUILT AROUND<br />YOUR WORK.</h2></div><p>Shared context from the control room<br />to the next investigation.</p></div><div className="use-case-grid">{[[Camera, 'OPERATORS', 'Keep the whole operation in view.', 'Monitor feeds and spot camera issues from a connected workspace.'], [Search, 'INVESTIGATORS', 'Spend less time finding the right frame.', 'Search records and follow detections back to the evidence.'], [Video, 'REVIEWERS', 'Bring context to every decision.', 'Inspect source footage and snapshots before drawing conclusions.']].map(([Icon, name, title, description]) => <article key={name}><Icon size={34} /><h3>{title}</h3><p>{description}</p><footer><span className="role-avatar"><Icon size={20} /></span><strong>{name}</strong><ArrowUpRight size={20} /></footer></article>)}</div></section>
    <section className="final-cta"><span className="cta-decoration" aria-hidden="true">SEE THE SIGNAL</span><div><span className="eyebrow">YOUR NEXT MOVE STARTS HERE</span><h2>SEE MORE.<br />MAKE IT <span className="outline-word">MATTER.</span></h2><p>Your footage has a story.<br />Get the workspace to bring it into focus.</p><EntryForm dark /></div></section>
    </main><footer className="landing-footer"><Brand /><p>Less noise. A clearer picture.</p><span>© {new Date().getFullYear()} NEXUS</span><a href="#main">Back to top ↑</a></footer>
  </div>;
}
